"""Описание миграции

Revision ID: 726498b48708
Revises: 8496548a8ff4
Create Date: 2025-06-22 00:14:53.817366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726498b48708'
down_revision: Union[str, None] = '8496548a8ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location')
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
