"""Update tables

Revision ID: 86b38de3754e
Revises: ac42eee04f6d
Create Date: 2024-04-05 04:14:08.719925

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86b38de3754e'
down_revision: Union[str, None] = 'ac42eee04f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'type')
    op.add_column('members', sa.Column('position', sa.String(), nullable=False))
    op.drop_column('members', 'text')
    op.drop_column('members', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('members', 'position')
    op.add_column('events', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
