"""Добавление фото

Revision ID: 9c42c3cae64a
Revises: 86b38de3754e
Create Date: 2024-04-10 18:01:16.056372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c42c3cae64a'
down_revision: Union[str, None] = '86b38de3754e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
