"""Ренейминг1

Revision ID: b2e18d2d8862
Revises: 1d4053c86476
Create Date: 2024-05-06 19:35:14.500836

"""
from typing import Sequence, Union

from alembic import op
import fastapi_storages
import sqlalchemy as sa
from app.database import storage

# revision identifiers, used by Alembic.
revision: str = 'b2e18d2d8862'
down_revision: Union[str, None] = '1d4053c86476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('photoUrl', fastapi_storages.integrations.sqlalchemy.FileType(storage), nullable=False))
    op.add_column('events', sa.Column('description', sa.String(), nullable=False))
    op.add_column('events', sa.Column('fullDescription', sa.String(), nullable=False))
    op.drop_column('events', 'big_text')
    op.drop_column('events', 'small_text')
    op.drop_column('events', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('small_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('big_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('events', 'fullDescription')
    op.drop_column('events', 'description')
    op.drop_column('events', 'photoUrl')
    # ### end Alembic commands ###
