"""Добавление фото

Revision ID: ee213e6da605
Revises: 9c42c3cae64a
Create Date: 2024-04-10 18:06:21.805538

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee213e6da605'
down_revision: Union[str, None] = '9c42c3cae64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
